### ISSUE TITLE
Get rid of useLayoutEffect warning in ssr

### ISSUE THREAD

**Issue by Chrisigrimm** [ejhammond/react-responsive-system#23]
I get a warning when using this lib in SSR mode. Sure the lib implemented SSR correctly but I still get a warning.
This could be "corrected" by using a hack like described in this post
https://medium.com/@alexandereardon/uselayouteffect-and-ssr-192986cdcf7a

I can implement it if wished.

**Comment by ejhammond** [comment]
Sorry I took a while off from updating this library; I didn't know anyone was using it! That's an interesting hack. I'll evaluate some options and try to push something soon. Thanks for the feedback!

**Comment by ejhammond** [comment]
I think that the workaround proposed in that medium article is actually not safe.

The main reason that we use `useLayoutEffect` rather than doing `useEffect` in the first place is to avoid a case where we render the wrong layout and then quickly swap it out for the correct layout. If we used `useEffect` our first render would always use the default screen class and then the second render would swap in the correct screen class.

When we bring SSR into the equation, we end up with a similar issue. On the server, we'll render the default screen class, then we'll send the HTML down and show it to the user, then we'll run our `useLayoutEffect` and realize that our server-rendered HTML was actually wrong and we'll swap it out for the correct screen class. But this time, there's also a potential for other undefined behavior because the SSR'd HTML _must_ match the initial client render in order to guarantee that Hydration succeeds.

Using an isomorphic solution doesn't solve that issue. If we use the hack from that medium article and we use `useEffect` on the server but keep `useLayoutEffect` on the client, the error will go away, but the (bug-prone) behavior will stay the same. We'll still render the default screen class on the server, show a flash of that incorrect layout on the client, then we'll swap out correct layout in (and hope that Hydration succeeds).

The fact is: if we don't know the correct screen class on the server, then we cannot possibly SSR the content correctly. So, the options are
1. Determine the correct screen class on the server and SSR using that screen class
2. Deal with the fact that the SSR'd content will be incorrect on the first render. I don't really like this solution.
3. Partially SSR, but skip over the responsive components and only render responsive components on the client.
4. Don't SSR at all

API ideas:
1. If you think you know the correct initial screen class on the server, great! We can add an `initialScreenClass` arg to `createResponsiveSystem` (we'd replace `defaultScreenClass` since `initial` is more correct) so that you can tell us what to render. Since you're controlling the initial render, we can use `useEffect` rather than `useLayoutEffect`, so the SSR error will go away and Hydration will work properly.
2. If you don't care if the first render is correct, then you can use the `initialScreenClass` and just hard-code a value. You'll get a quick flash of the incorrect layout and then it'll fix itself. Again, you're controlling the first render so we'll be using `useEffect`  and we shouldn't have any SSR  errors and Hydration should be fine.
3. If you do care about the first render, but you don't want to figure out the correct screen class on the server, you can pass `initialScreenClass={null}` and then render placeholder content (loaders / skeletons etc) until you have a proper screen class. This is a lot of work, and getting the right placeholder content could be a challenge, but it's an option.
4. If you don't SSR, then don't provide `initialScreenClass` at all and we'll continue to use `useLayoutEffect`. SSR errors and Hydration are not relevant, and we won't see a flash of incorrect layout because we're using `useLayoutEffect`

**Comment by ejhammond** [comment]
Fixed in [c39c347](https://github.com/ejhammond/react-responsive-system/commit/c39c34768aceb0f15d84f112d8f1ee420b8ae1ae)
